### PR TITLE
Circle CreateItems.cs

### PR DESCRIPTION
**Pull request by jekser2**
Created a version of this key overlay to be shape a circle 

As well ass added other stuff

- from the how many sides the bar have (this must be above 2)
- the bar rotation
- and automatically ajusting window to key amount

### CODE REVIEW

**Comment by Blondazz** [comment]
Hello. This is cool but that PR overwrites my existing code and i cannot merge it into the repo like that. Please make a version that would have both of them. Also please put all of your changes in one pull request.

**Comment by jekser2** [comment]
This is my first time doing a gut repo and im not a coder my self. I
modified the code entirely to create a different version instead of merging
but i cant get any of your contacts to create my own git repo. That was the
goal not to create a merge sorry if it was confusing. This is my first time
using github and making a contribution

**Comment by Blondazz** [comment]
I'm not sure if I understand, you already created your own repo by forking mine. And what do you mean by contacts?

**Comment by Blondazz** [comment]
Hi I'm the owner haha. Friedchicken repo is also forked. Fork is basically just creating a copy of the original code and based on the license that I set for the repo (GPL-3.0 license) you are free to do whatever you want with it after forking and I could use your solutions in my own code as well. So if you want it to be your own "version" then you are already set. If you have any other questions regarding github and git in general just hit me up on discord. Blondazz#4321

**Comment by jekser2** [comment]
Thank you very much. Sorry for any  inconvenience i made.

**Pull request closed without merging**
